<?php

/**
 * Implementation of hook_schema().
 */
/*
function mitest_schema() {
  // This should always point to our 'current' schema. This makes it relatively easy
  // to keep a record of schema as we make changes to it.
  return panels_schema_3();
}
*/
function featureoa_install() {
  //drupal_install_schemafeatureoaba');
}

/**
 * Implementation of hook_uninstall().
 */
function featureoa_uninstall() {
 //drupal_uninstall_schema('featureoa');
}
